services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000 # Replace with your user ID and group ID
    ports:
      - "8096:8096"
      - "8920:8920"
    volumes:
      - /mnt/SMBShare/Media:/media
    restart: unless-stopped
