version: "3.8"

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/LosAngeles
    volumes:
      - /Users/mattrose570/Docker/sonarr/config
      - /mnt/smbShare:/Volumes/SMB/Media/Shows
      - /Volumes/SMB/Media
    ports:
      - 8989:8989
    restart: unless-stopped
