---
services:
  ddclient:
    image: lscr.io/linuxserver/ddclient:latest
    container_name: ddclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/LosAngeles
    volumes:
      - /path/to/ddclient/config:/config
    restart: unless-stopped
